SELECT
	tiempo,
	COALESCE(NULLIF(AAVE_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(ADA_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(APT_USDT::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(ARB_USDT::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(ATOM_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(AVAX_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(BCH_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(BTC_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(DOGE_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(DOT_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(ETC_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(ETH_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(FIL_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(HBAR_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(INJ_USDT::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(LINK_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(LTC_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(MANA_USDT::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(MATIC_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(NEAR_USDT::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(NEO_USDT::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(OP_USDT::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(RENDER_USDT::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(RUNE_USDT::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(SAND_USDT::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(SNX_USDT::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(SOL_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(STX_USDT::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(THETA_USDT::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(XRP_USD::TEXT, 'NaN')::NUMERIC, 0) + 
    COALESCE(NULLIF(UNI_USD::TEXT, 'NaN')::NUMERIC, 0) AS total_suma 
	
	FROM public.valores
ORDER BY tiempo DESC 
limit 150